# Un playbook è il file che descrive cosa Ansible deve fare e su quali host.
# Collega i gruppi di host (segnalati dall'inventory) alla logica da applicare (task o ruoli), definendo l'ordine e le condizioni di esecuzione. 
# I tags definiti nei ruoli possono essere usati per eseguire solo una parte del playbook, invece di tutto il playbook.
- name:  Configurazione dell'ambiente richiesto dallo step 5
  hosts: all
  gather_facts: true
  become: true
  roles:
    - role: podman
    - role: podman_network
    - role: registry
    - role: container_images
    - role: container_run
    - role: jenkins_controller
    - role: jenkins_agent