---

# Path della directory sulla VM dedicata al build context
container_images_context_dir: /var/tmp/ansible-image-builds

# Determina il prefisso del nome immagine, che viene utilizzato da podman per sapere su quale registry fare il push.
# Se vuoto, le immagini vengono buildate solo localmente e non vengono pushate su alcun registry. 
container_images_registry: ""

# Default per l'arg utilizzato da extra_vars per la build delle immagini
container_images_ssh_user: ansible

# Default per l'arg utilizzato da extra_vars per la build delle immagini, vuoto perchè la chiave pubblica deve essere passata al ruolo
container_images_ssh_pubkey: ""


# Se true la build viene rifatta anche quando nome:tag esiste gia'
container_images_force_rebuild: true

# Lista di dizionari che contiene i dati di ciascuna immagine da buildare.
# Deve essere coerente con la struttura di cartelle messe in containerfiles/
container_images_builds:
  - name: debian-os
    tag: "1.0.0"
    path: debian
    ssh_port: 2201
  - name: rocky-os
    tag: "1.0.0"
    path: rocky   # rappresenta il path alla cartella dedicata all'os dentro containerfiles/
    ssh_port: 2202




# Se true, dopo la build pusha verso il registry ricavato dal nome.
container_images_push: true