# Un playbook è il file che descrive cosa Ansible deve fare e su quali host.
# Collega i gruppi di host (segnalati dall'inventory) alla logica da applicare (task o ruoli), definendo l'ordine e le condizioni di esecuzione. 
# I tags definiti nei ruoli possono essere usati per eseguire solo una parte del playbook, invece di tutto il playbook.
---

- name: Build delle immagini base sulla VM
  hosts: all
  become: true
  
  roles:
    - role: podman
    - role: container_images