// Blocco radice che apre la pipeline
pipeline {
    // Definisce su quale nodo far girare la pipeline, in questo caso su qualsiasi nodo che abbia il tag "build"
    agent { label 'build' }
    
    // Definisce variabili d'ambiente valide in tutta la pipeline. Ogni stage può accedere ai valori definiti attraverso l'oggetto env
    // L'oggetto env contiene sia le variabili di ambiente definite in environment, sia le variabili create automaticamente da jenkins
    environment {
        // Coordinate dell'immagine e del registry
        REGISTRY   = 'localhost:5000'
        IMAGE_REPO = 'app-demo'
        IMAGE_NAME = "${REGISTRY}/${IMAGE_REPO}"

        // Percorso al Socket Podman dell'host con stringa URI, montato nell'agent (per DooD).
        CONTAINER_HOST = 'unix:///run/podman/podman.sock'
    }
    
    // Definisce i vari stage della pipeline, ogni stage presenta un nome ed è composto da vari steps
    stages {
        stage('Determina il tag immagine') {
            // Steps necessari per determinare quale tag dare all'immagine docker
            steps {
                //script apre una zona di script Groovy, utile in caso bisogni implementare una logica che la sintassi dichiarativa non permette
                script {

                env.IMAGE_TAG = "1.0.${env.BUILD_NUMBER}"
                echo "Immagine: ${IMAGE_NAME}:${env.IMAGE_TAG}"

              }
            }
        }
        // Steps per buildare l'immagine sull'host (Dood)
        stage('Build immagine') {
            // Step che utilizza il comando sh per eseguire un comando shell sull'agent
            steps {
                // podman --remote build dice alla podman CLI di far eseguire la build all'host
                // la flag -t assegna il nome all'immagine
                // la flag -f segnala dove si trova il DockerFile
                sh '''
                    podman --remote build \
                        -t ${IMAGE_NAME}:${IMAGE_TAG} \
                        -f app/Dockerfile app
                '''
            }
        }
        
        // Steps per pushare l'immagine buildata su dockerhub
        stage('Push sul registry') {
            steps {
                sh 'podman --remote push ${IMAGE_NAME}:${IMAGE_TAG}'
            }
        }

        stage('Deploy sul container target') {
            steps {
                withCredentials([sshUserPrivateKey(
                credentialsId: 'target-ssh-key',
                keyFileVariable: 'SSH_KEY',
                usernameVariable: 'SSH_USER'
        )]) {
            
            sh '''
                ansible-playbook deploy.yml \
                  -i "rocky-os," \
                  -u "${SSH_USER}" \
                  --private-key "${SSH_KEY}" \
                  -e "image=${IMAGE_NAME}:${IMAGE_TAG}"
            '''
        }
            }
        }
    }

}